import blogData from "@/data/blog/posts.json";

/*
 * BLOG DATA ACCESS LAYER
 *
 * UI → lib/blog → data/blog/posts.json (generated by scripts/build-blog.mjs)
 *
 * The generated file is the single content source. The build script
 * validates every record before the site exists; this layer adds a
 * runtime normalization pass (defense in depth — one corrupted
 * record is filtered out, never a crash) and memoizes derived
 * indexes so interactive filtering never re-scans or re-sorts.
 *
 * Content data (this file) is immutable at runtime: derived maps are
 * built once at module scope.
 */

export type BlogPostCover = {
  src: string;
  alt: string;
  width: number;
  height: number;
};

export type BlogPostMeta = {
  slug: string;
  title: string;
  subtitle: string | null;
  excerpt: string;
  description: string;
  date: string;
  updated: string | null;
  author: string;
  category: string;
  tags: string[];
  readingMinutes: number;
  readingTime: string;
  featured: boolean;
  cover: BlogPostCover | null;
  wordCount: number;
};

export type BlogPost = BlogPostMeta & {
  html: string;
  headings: { id: string; text: string; level: number }[];
};

type RawBlogData = {
  version: number;
  generatedAt: string;
  basePath: string;
  siteUrl: string;
  siteName: string;
  siteDescription: string;
  posts: unknown[];
  indexes: {
    tags: Record<string, string[]>;
    categories: Record<string, string[]>;
    related: Record<string, string[]>;
    adjacent: Record<string, { prev: string | null; next: string | null }>;
  };
};

function isNonEmptyString(
  value: unknown
): value is string {
  return (
    typeof value === "string" &&
    value.length > 0
  );
}

function isPostRecord(
  value: unknown
): value is BlogPost {
  if (typeof value !== "object" || value === null) {
    return false;
  }

  const candidate = value as Record<string, unknown>;

  return (
    isNonEmptyString(candidate.slug) &&
    isNonEmptyString(candidate.title) &&
    isNonEmptyString(candidate.excerpt) &&
    isNonEmptyString(candidate.date) &&
    isNonEmptyString(candidate.author) &&
    isNonEmptyString(candidate.category) &&
    typeof candidate.html === "string" &&
    Array.isArray(candidate.tags) &&
    candidate.tags.every(isNonEmptyString)
  );
}

const RAW_DATA = blogData as unknown as RawBlogData;

/*
 * Normalization: invalid optional records are dropped instead of
 * poisoning the catalogue. Sort order is re-derived defensively so
 * the UI never depends on the generator having ordered the file.
 */
const POSTS: BlogPost[] = RAW_DATA.posts
  .filter(isPostRecord)
  .sort((a, b) =>
    a.date < b.date ? 1 : a.date > b.date ? -1 : a.slug < b.slug ? -1 : 1
  );

const BY_SLUG = new Map(POSTS.map((post) => [post.slug, post]));

/*
 * Lightweight metadata list for the index page and client islands —
 * no article HTML bodies ship to list views.
 */
const META_LIST: BlogPostMeta[] = POSTS.map(
  ({
    html: _html,
    headings: _headings,
    ...meta
  }) => meta
);

const TAGS: string[] = Object.keys(
  RAW_DATA.indexes?.tags ?? {}
);

const CATEGORIES: string[] = Object.keys(
  RAW_DATA.indexes?.categories ?? {}
);

const FEATURED = META_LIST.filter((post) => post.featured);

const EMPTY_ADJACENT = { prev: null, next: null };

export function getBlogInfo() {
  return {
    generatedAt: RAW_DATA.generatedAt,
    siteName: RAW_DATA.siteName,
    siteDescription: RAW_DATA.siteDescription
  };
}

export function getBlogMetaList(): readonly BlogPostMeta[] {
  return META_LIST;
}

export function getFeaturedPost(): BlogPostMeta | null {
  return FEATURED[0] ?? null;
}

export function getPost(slug: string): BlogPost | null {
  return BY_SLUG.get(slug) ?? null;
}

export function getAllTags(): readonly string[] {
  return TAGS;
}

export function getAllCategories(): readonly string[] {
  return CATEGORIES;
}

export function getPostsByTag(tag: string): readonly BlogPostMeta[] {
  const slugs = RAW_DATA.indexes?.tags?.[tag] ?? [];
  return slugs
    .map((slug) => BY_SLUG.get(slug))
    .filter((post): post is BlogPost => post !== undefined)
    .map(({ html: _html, headings: _headings, ...meta }) => meta);
}

export function getPostsByCategory(
  category: string
): readonly BlogPostMeta[] {
  const slugs = RAW_DATA.indexes?.categories?.[category] ?? [];
  return slugs
    .map((slug) => BY_SLUG.get(slug))
    .filter((post): post is BlogPost => post !== undefined)
    .map(({ html: _html, headings: _headings, ...meta }) => meta);
}

export function getRelatedPosts(
  slug: string
): readonly BlogPostMeta[] {
  const slugs = RAW_DATA.indexes?.related?.[slug] ?? [];
  return slugs
    .map((relatedSlug) => BY_SLUG.get(relatedSlug))
    .filter((post): post is BlogPost => post !== undefined)
    .map(({ html: _html, headings: _headings, ...meta }) => meta);
}

export function getAdjacentPosts(
  slug: string
): { prev: BlogPostMeta | null; next: BlogPostMeta | null } {
  const adjacent =
    RAW_DATA.indexes?.adjacent?.[slug] ?? EMPTY_ADJACENT;

  const resolve = (
    adjacentSlug: string | null
  ): BlogPostMeta | null => {
    if (adjacentSlug === null) {
      return null;
    }

    const post = BY_SLUG.get(adjacentSlug);

    if (!post) {
      return null;
    }

    const { html: _html, headings: _headings, ...meta } = post;

    return meta;
  };

  return {
    prev: resolve(adjacent.prev),
    next: resolve(adjacent.next)
  };
}

export function getBlogPostCount(): number {
  return POSTS.length;
}

export function isBlogEmpty(): boolean {
  return POSTS.length === 0;
}

/*
 * Format an ISO date (YYYY-MM-DD) for display without depending on
 * the runtime locale — deterministic static output.
 */
export function formatBlogDate(
  isoDate: string
): string {
  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
  ];

  const match = isoDate.match(
    /^(\d{4})-(\d{2})-(\d{2})$/
  );

  if (!match) {
    return isoDate;
  }

  const [, year, month, day] = match;

  return `${months[Number(month) - 1]} ${Number(day)}, ${year}`;
}

/*
 * Compact variant for card meta rows.
 */
export function formatBlogDateShort(
  isoDate: string
): string {
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec"
  ];

  const match = isoDate.match(
    /^(\d{4})-(\d{2})-(\d{2})$/
  );

  if (!match) {
    return isoDate;
  }

  const [, year, month, day] = match;

  return `${months[Number(month) - 1]} ${Number(day)}, ${year}`;
}
