import blogData from "@/data/blog/posts.json";

import type {
  BlogPost,
  BlogPostMeta,
  RelatedPostEntry
} from "@/lib/blogFormat";

/*
 * BLOG DATA ACCESS LAYER — SERVER SIDE.
 *
 * UI → lib/blog → data/blog/posts.json (generated by scripts/build-blog.mjs)
 *
 * This module imports the full generated content file (including
 * article HTML) and therefore MUST stay server-side. Client
 * components must import from lib/blogFormat.ts instead — that module
 * carries types and formatters only. This boundary is what keeps
 * article bodies out of every client bundle: list views receive
 * metadata as serialized props, article HTML is rendered into static
 * HTML at build time, and no client chunk ever contains posts.json.
 *
 * The build script validates every record before the site exists;
 * this layer adds a runtime normalization pass (defense in depth —
 * one corrupted record is filtered out, never a crash) and memoizes
 * derived indexes at module scope so interactive filtering never
 * re-scans or re-sorts.
 *
 * Content data (this file) is immutable at runtime: derived maps are
 * built once at module scope.
 */

export type {
  BlogPost,
  BlogPostCover,
  BlogPostMeta,
  RelatedPostEntry
} from "@/lib/blogFormat";

/*
 * A resolved related-article reference: the target's metadata plus
 * the relationship's provenance (author-explicit vs scored) and —
 * for scored entries (v2.5.5) — the strongest concrete overlap
 * signals the build model found, for the tiny "why related" hints.
 */
export type RelatedPost = {
  post: BlogPostMeta;
  score: number | null;
  explicit: boolean;
  shared: readonly string[];
};

export {
  formatBlogDate,
  formatBlogDateShort
} from "@/lib/blogFormat";

type RawBlogData = {
  version: number;
  generatedAt: string;
  basePath: string;
  siteUrl: string;
  siteName: string;
  siteDescription: string;
  posts: unknown[];
  indexes: {
    tags: Record<string, string[]>;
    categories: Record<string, string[]>;
    related: Record<string, RelatedPostEntry[]>;
    adjacent: Record<string, { prev: string | null; next: string | null }>;
    linksHere?: Record<string, string[]>;
  };
};

function isNonEmptyString(
  value: unknown
): value is string {
  return (
    typeof value === "string" &&
    value.length > 0
  );
}

function isPostRecord(
  value: unknown
): value is BlogPost {
  if (typeof value !== "object" || value === null) {
    return false;
  }

  const candidate = value as Record<string, unknown>;

  return (
    isNonEmptyString(candidate.slug) &&
    isNonEmptyString(candidate.title) &&
    isNonEmptyString(candidate.excerpt) &&
    isNonEmptyString(candidate.date) &&
    isNonEmptyString(candidate.author) &&
    isNonEmptyString(candidate.category) &&
    typeof candidate.html === "string" &&
    Array.isArray(candidate.tags) &&
    candidate.tags.every(isNonEmptyString)
  );
}

const RAW_DATA = blogData as unknown as RawBlogData;

/*
 * Normalization: invalid optional records are dropped instead of
 * poisoning the catalogue. Sort order is re-derived defensively so
 * the UI never depends on the generator having ordered the file.
 */
const POSTS: BlogPost[] = RAW_DATA.posts
  .filter(isPostRecord)
  .sort((a, b) =>
    a.date < b.date ? 1 : a.date > b.date ? -1 : a.slug < b.slug ? -1 : 1
  );

const BY_SLUG = new Map(POSTS.map((post) => [post.slug, post]));

/*
 * Stripped references (not copies) of the module records: the meta
 * projection omits html/headings but shares the underlying objects, so
 * no duplicate article data exists in memory.
 */
function toMeta(post: BlogPost): BlogPostMeta {
  const { html: _html, headings: _headings, ...meta } = post;

  return meta;
}

/*
 * Lightweight metadata list for the index page and client islands —
 * no article HTML bodies ship to list views.
 */
const META_LIST: BlogPostMeta[] = POSTS.map(toMeta);

const TAGS: string[] = Object.keys(
  RAW_DATA.indexes?.tags ?? {}
);

const CATEGORIES: string[] = Object.keys(
  RAW_DATA.indexes?.categories ?? {}
);

const FEATURED = META_LIST.filter((post) => post.featured);

const EMPTY_ADJACENT = { prev: null, next: null };

export function getBlogInfo() {
  return {
    generatedAt: RAW_DATA.generatedAt,
    siteName: RAW_DATA.siteName,
    siteDescription: RAW_DATA.siteDescription
  };
}

export function getBlogMetaList(): readonly BlogPostMeta[] {
  return META_LIST;
}

export function getFeaturedPost(): BlogPostMeta | null {
  return FEATURED[0] ?? null;
}

export function getPost(slug: string): BlogPost | null {
  return BY_SLUG.get(slug) ?? null;
}

export function getAllTags(): readonly string[] {
  return TAGS;
}

export function getAllCategories(): readonly string[] {
  return CATEGORIES;
}

export function getPostsByTag(tag: string): readonly BlogPostMeta[] {
  const slugs = RAW_DATA.indexes?.tags?.[tag] ?? [];
  return slugs
    .map((slug) => BY_SLUG.get(slug))
    .filter((post): post is BlogPost => post !== undefined)
    .map(toMeta);
}

export function getPostsByCategory(
  category: string
): readonly BlogPostMeta[] {
  const slugs = RAW_DATA.indexes?.categories?.[category] ?? [];
  return slugs
    .map((slug) => BY_SLUG.get(slug))
    .filter((post): post is BlogPost => post !== undefined)
    .map(toMeta);
}

/*
 * Related articles for a slug, resolved to metadata and validated at
 * runtime (defense in depth on top of the build's graph validation):
 * unknown targets, self-references, and duplicates are dropped, never
 * rendered. Order comes straight from the deterministic index —
 * explicit author relationships first, then by descending score.
 */
export function getRelatedPosts(
  slug: string
): RelatedPost[] {
  const entries =
    RAW_DATA.indexes?.related?.[slug] ?? [];

  const resolved: RelatedPost[] = [];
  const seen = new Set<string>([slug]);

  for (const entry of entries) {
    if (
      typeof entry?.slug !== "string" ||
      seen.has(entry.slug)
    ) {
      continue;
    }

    const post = BY_SLUG.get(entry.slug);

    if (!post) {
      continue;
    }

    seen.add(entry.slug);

    /*
     * Runtime defense for the shared signals (v2.5.5): only strings
     * survive, capped at 4 — a malformed index entry can never
     * inject markup-bearing data into the page (rendering is plain
     * text anyway, but the data stays honest).
     */
    const shared = Array.isArray(entry.shared)
      ? entry.shared
          .filter(
            (signal): signal is string =>
              typeof signal === "string" && signal.length > 0
          )
          .slice(0, 4)
      : [];

    resolved.push({
      post: toMeta(post),
      score:
        typeof entry.score === "number"
          ? entry.score
          : null,
      explicit: entry.explicit === true,
      shared
    });
  }

  return resolved;
}

/*
 * "What links here" (v2.5.4): the inverted body-link graph. For a
 * slug, every OTHER article whose prose hyperlinks into it, resolved
 * to metadata and validated at runtime (defense in depth — unknown
 * targets, self-references, and duplicates are dropped, never
 * rendered). Order comes straight from the build's deterministic
 * source scan (date descending, slug ascending).
 */
export function getLinksHere(
  slug: string
): BlogPostMeta[] {
  const slugs =
    RAW_DATA.indexes?.linksHere?.[slug] ?? [];

  const resolved: BlogPostMeta[] = [];
  const seen = new Set<string>([slug]);

  for (const entry of slugs) {
    if (
      typeof entry !== "string" ||
      seen.has(entry)
    ) {
      continue;
    }

    const post = BY_SLUG.get(entry);

    if (!post) {
      continue;
    }

    seen.add(entry);

    resolved.push(toMeta(post));
  }

  return resolved;
}

/*
 * Inbound reference counts (v2.5.5): for every slug with at least
 * one inbound body link, the number of articles whose prose links
 * into it. Surfaced as quiet "↩ N" badges on the blog-index cards
 * and in the article header (linking to the REFERENCED BY section).
 * Derived from the SAME validated build-time graph getLinksHere
 * reads — no second source of truth.
 */
export function getInboundCounts(): Record<string, number> {
  const counts: Record<string, number> = {};

  const linksHere = RAW_DATA.indexes?.linksHere;

  if (!linksHere) {
    return counts;
  }

  for (const [slug, sources] of Object.entries(linksHere)) {
    if (Array.isArray(sources) && sources.length > 0) {
      counts[slug] = sources.length;
    }
  }

  return counts;
}

export function getAdjacentPosts(
  slug: string
): { prev: BlogPostMeta | null; next: BlogPostMeta | null } {
  const adjacent =
    RAW_DATA.indexes?.adjacent?.[slug] ?? EMPTY_ADJACENT;

  const resolve = (
    adjacentSlug: string | null
  ): BlogPostMeta | null => {
    if (adjacentSlug === null) {
      return null;
    }

    const post = BY_SLUG.get(adjacentSlug);

    if (!post) {
      return null;
    }

    return toMeta(post);
  };

  return {
    prev: resolve(adjacent.prev),
    next: resolve(adjacent.next)
  };
}

export function getBlogPostCount(): number {
  return POSTS.length;
}

export function isBlogEmpty(): boolean {
  return POSTS.length === 0;
}
