import blogData from "@/data/blog/posts.json";

import type {
  BlogPost,
  BlogPostMeta
} from "@/lib/blogFormat";

/*
 * BLOG DATA ACCESS LAYER — SERVER SIDE.
 *
 * UI → lib/blog → data/blog/posts.json (generated by scripts/build-blog.mjs)
 *
 * This module imports the full generated content file (including
 * article HTML) and therefore MUST stay server-side. Client
 * components must import from lib/blogFormat.ts instead — that module
 * carries types and formatters only. This boundary is what keeps
 * article bodies out of every client bundle: list views receive
 * metadata as serialized props, article HTML is rendered into static
 * HTML at build time, and no client chunk ever contains posts.json.
 *
 * The build script validates every record before the site exists;
 * this layer adds a runtime normalization pass (defense in depth —
 * one corrupted record is filtered out, never a crash) and memoizes
 * derived indexes at module scope so interactive filtering never
 * re-scans or re-sorts.
 *
 * Content data (this file) is immutable at runtime: derived maps are
 * built once at module scope.
 */

export type {
  BlogPost,
  BlogPostCover,
  BlogPostMeta
} from "@/lib/blogFormat";

export {
  formatBlogDate,
  formatBlogDateShort
} from "@/lib/blogFormat";

type RawBlogData = {
  version: number;
  generatedAt: string;
  basePath: string;
  siteUrl: string;
  siteName: string;
  siteDescription: string;
  posts: unknown[];
  indexes: {
    tags: Record<string, string[]>;
    categories: Record<string, string[]>;
    related: Record<string, string[]>;
    adjacent: Record<string, { prev: string | null; next: string | null }>;
  };
};

function isNonEmptyString(
  value: unknown
): value is string {
  return (
    typeof value === "string" &&
    value.length > 0
  );
}

function isPostRecord(
  value: unknown
): value is BlogPost {
  if (typeof value !== "object" || value === null) {
    return false;
  }

  const candidate = value as Record<string, unknown>;

  return (
    isNonEmptyString(candidate.slug) &&
    isNonEmptyString(candidate.title) &&
    isNonEmptyString(candidate.excerpt) &&
    isNonEmptyString(candidate.date) &&
    isNonEmptyString(candidate.author) &&
    isNonEmptyString(candidate.category) &&
    typeof candidate.html === "string" &&
    Array.isArray(candidate.tags) &&
    candidate.tags.every(isNonEmptyString)
  );
}

const RAW_DATA = blogData as unknown as RawBlogData;

/*
 * Normalization: invalid optional records are dropped instead of
 * poisoning the catalogue. Sort order is re-derived defensively so
 * the UI never depends on the generator having ordered the file.
 */
const POSTS: BlogPost[] = RAW_DATA.posts
  .filter(isPostRecord)
  .sort((a, b) =>
    a.date < b.date ? 1 : a.date > b.date ? -1 : a.slug < b.slug ? -1 : 1
  );

const BY_SLUG = new Map(POSTS.map((post) => [post.slug, post]));

/*
 * Stripped references (not copies) of the module records: the meta
 * projection omits html/headings but shares the underlying objects, so
 * no duplicate article data exists in memory.
 */
function toMeta(post: BlogPost): BlogPostMeta {
  const { html: _html, headings: _headings, ...meta } = post;

  return meta;
}

/*
 * Lightweight metadata list for the index page and client islands —
 * no article HTML bodies ship to list views.
 */
const META_LIST: BlogPostMeta[] = POSTS.map(toMeta);

const TAGS: string[] = Object.keys(
  RAW_DATA.indexes?.tags ?? {}
);

const CATEGORIES: string[] = Object.keys(
  RAW_DATA.indexes?.categories ?? {}
);

const FEATURED = META_LIST.filter((post) => post.featured);

const EMPTY_ADJACENT = { prev: null, next: null };

export function getBlogInfo() {
  return {
    generatedAt: RAW_DATA.generatedAt,
    siteName: RAW_DATA.siteName,
    siteDescription: RAW_DATA.siteDescription
  };
}

export function getBlogMetaList(): readonly BlogPostMeta[] {
  return META_LIST;
}

export function getFeaturedPost(): BlogPostMeta | null {
  return FEATURED[0] ?? null;
}

export function getPost(slug: string): BlogPost | null {
  return BY_SLUG.get(slug) ?? null;
}

export function getAllTags(): readonly string[] {
  return TAGS;
}

export function getAllCategories(): readonly string[] {
  return CATEGORIES;
}

export function getPostsByTag(tag: string): readonly BlogPostMeta[] {
  const slugs = RAW_DATA.indexes?.tags?.[tag] ?? [];
  return slugs
    .map((slug) => BY_SLUG.get(slug))
    .filter((post): post is BlogPost => post !== undefined)
    .map(toMeta);
}

export function getPostsByCategory(
  category: string
): readonly BlogPostMeta[] {
  const slugs = RAW_DATA.indexes?.categories?.[category] ?? [];
  return slugs
    .map((slug) => BY_SLUG.get(slug))
    .filter((post): post is BlogPost => post !== undefined)
    .map(toMeta);
}

export function getRelatedPosts(
  slug: string
): readonly BlogPostMeta[] {
  const slugs = RAW_DATA.indexes?.related?.[slug] ?? [];
  return slugs
    .map((relatedSlug) => BY_SLUG.get(relatedSlug))
    .filter((post): post is BlogPost => post !== undefined)
    .map(toMeta);
}

export function getAdjacentPosts(
  slug: string
): { prev: BlogPostMeta | null; next: BlogPostMeta | null } {
  const adjacent =
    RAW_DATA.indexes?.adjacent?.[slug] ?? EMPTY_ADJACENT;

  const resolve = (
    adjacentSlug: string | null
  ): BlogPostMeta | null => {
    if (adjacentSlug === null) {
      return null;
    }

    const post = BY_SLUG.get(adjacentSlug);

    if (!post) {
      return null;
    }

    return toMeta(post);
  };

  return {
    prev: resolve(adjacent.prev),
    next: resolve(adjacent.next)
  };
}

export function getBlogPostCount(): number {
  return POSTS.length;
}

export function isBlogEmpty(): boolean {
  return POSTS.length === 0;
}
