/*
 * BRAND ASSET URLS — the single place the site resolves generated
 * brand assets. Server and client components both inline
 * NEXT_PUBLIC_BASE_PATH at build time, so every URL below carries the
 * deployment basePath (/WEB in production) exactly once, here.
 *
 * The referenced files are generated by scripts/generate-brand.mjs
 * and committed at public/brand/ (runtime copies of the canonical
 * assets/brand/ system — see assets/README.md).
 *
 * Usage law (v2.9):
 * - the star is the PRIMARY site identity: headers, footer, favicon,
 *   loading surfaces, social artwork
 * - RedEye remains RED MAGIC's own artistic mark, never the site logo
 * - decorative renderings must be aria-hidden; the logo link carries
 *   its accessible name on the <a> that wraps it
 */

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export const BRAND_STAR = {
  /** Primary header/footer mark (solid brand red). */
  red: `${BASE_PATH}/brand/star-red.svg`,
  /** Red-hot gradient — identity/loading surfaces. */
  redHot: `${BASE_PATH}/brand/star-red-hot.svg`,
  /** Monochrome white — dark surfaces and lockups. */
  white: `${BASE_PATH}/brand/star-white.svg`,
  /** Transparent-stroke red — decorative echoes. */
  outlineRed: `${BASE_PATH}/brand/star-outline-red.svg`,
  /** Neutral silver — quiet dark-UI accents. */
  silver: `${BASE_PATH}/brand/star-silver.svg`
} as const;

/** Intrinsic geometry of the served star SVGs (viewBox 0 0 100 100). */
export const BRAND_STAR_VIEWBOX = {
  width: 100,
  height: 100
} as const;
